import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import { PGlite } from "@electric-sql/pglite";
import { drizzle as drizzlePglite } from "drizzle-orm/pglite";
import { sql } from "drizzle-orm";
import * as schema from "./schema/index.js";
import { BADGE_SEEDS, type BadgeSeed } from "./seed-badges.js";
import { seedExamples } from "./seed-examples.js";
import { readFileSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import bcrypt from "bcryptjs";

const { Pool } = pg;

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export let db: any;
export let pool: any;

let _pglite: PGlite | null = null;
let _bootstrapped = false;

if (process.env.DATABASE_URL) {
  pool = new Pool({ connectionString: process.env.DATABASE_URL });
  db = drizzle(pool, { schema });
} else {
  console.log("No DATABASE_URL found, using PGlite (in-memory) for development.");
  _pglite = new PGlite("");
  db = drizzlePglite(_pglite, { schema });
}

/** Locate the drizzle migrations directory regardless of dev/built layout. */
function findMigrationsDir(): string | null {
  // From lib/db/dist (built) or lib/db/src (dev), the drizzle folder is one
  // or two levels up. From a downstream artifact bundle (e.g. api-server/dist
  // with @workspace/db inlined), we need to climb further until we find it.
  const candidates = [
    path.resolve(__dirname, "../drizzle"),
    path.resolve(__dirname, "../../drizzle"),
    path.resolve(__dirname, "../../../lib/db/drizzle"),
    path.resolve(__dirname, "../../../../lib/db/drizzle"),
    path.resolve(process.cwd(), "lib/db/drizzle"),
    path.resolve(process.cwd(), "../../lib/db/drizzle"),
  ];
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  return null;
}

async function applyPgliteMigrations(pglite: PGlite): Promise<void> {
  const dir = findMigrationsDir();
  if (!dir) {
    console.warn("[db] No migrations directory found — skipping bootstrap.");
    return;
  }
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  for (const file of files) {
    const sqlText = readFileSync(path.join(dir, file), "utf8");
    try {
      await pglite.exec(sqlText);
      console.log(`[db] applied migration ${file}`);
    } catch (err: any) {
      // PGlite throws on duplicate-table when re-running. We use IF NOT EXISTS
      // in 0001 but 0000 is generated by drizzle-kit and is not idempotent;
      // tolerate "already exists" so callers can run bootstrap repeatedly.
      const msg = String(err?.message ?? err);
      if (!/already exists|duplicate/i.test(msg)) {
        throw err;
      }
    }
  }
}

async function seedAdminUser(): Promise<void> {
  const hash = await bcrypt.hash("guzo-admin-2026", 10);
  await db
    .insert(schema.usersTable)
    .values({
      email: "admin@guzo.app",
      name: "Abune Guzo",
      passwordHash: hash,
      role: "superadmin",
    })
    .onConflictDoNothing();

  // Owner superadmin — password is reset on every bootstrap so the credentials
  // stay deterministic in PGlite (in-memory) and on fresh deployments.
  const ownerHash = await bcrypt.hash("Dagi1431.", 10);
  await db
    .insert(schema.usersTable)
    .values({
      email: "crossdagi@gmail.com",
      name: "Dagi",
      passwordHash: ownerHash,
      role: "superadmin",
    })
    .onConflictDoUpdate({
      target: schema.usersTable.email,
      set: {
        passwordHash: ownerHash,
        role: "superadmin",
        status: "active",
      },
    });
}

async function seedBadges(): Promise<void> {
  for (const b of BADGE_SEEDS) {
    await db
      .insert(schema.badgesTable)
      .values({
        key: b.key,
        name: b.name,
        description: b.description,
        iconKey: b.iconKey,
        tier: b.tier,
        sortOrder: b.sortOrder,
      })
      .onConflictDoUpdate({
        target: schema.badgesTable.key,
        set: {
          name: b.name,
          description: b.description,
          iconKey: b.iconKey,
          tier: b.tier,
          sortOrder: b.sortOrder,
        },
      });
  }
}

/**
 * Apply migrations and seed reference data. Safe to call repeatedly.
 * - With `DATABASE_URL`: assumes drizzle-kit push handled schema; only seeds.
 * - Without `DATABASE_URL` (in-memory PGlite): also applies SQL migrations.
 *
 * The api-server calls this before `app.listen()`.
 */
export async function bootstrap(): Promise<void> {
  if (_bootstrapped) return;
  _bootstrapped = true;
  try {
    if (_pglite) {
      await applyPgliteMigrations(_pglite);
    } else {
      // Live Postgres path — assume drizzle push has run; just verify
      // the connection is alive.
      await db.execute(sql`select 1`);
    }
    await seedAdminUser();
    await seedBadges();
    if (_pglite || process.env.SEED_ON_BOOTSTRAP === "true") {
      console.log("[db] seeding example data...");
      await seedExamples(db);
    }
    console.log("[db] bootstrap complete");
  } catch (err) {
    console.error("[db] bootstrap failed", err);
    throw err;
  }
}

export * from "./schema";
export { BADGE_SEEDS, type BadgeSeed } from "./seed-badges";
